### ISSUE TITLE
连接CORS网使用的问题？

### ISSUE THREAD

**Issue by huaxiaoxuan7** [dxhbiz/ntrip-decoder#5]
厉害 这个库太棒了

**Comment by huaxiaoxuan7** [comment]
`
client.on('data', data => decoder.decode(data));
decoder.on('data', data => BD982.write(data));
`

**Comment by dxhbiz** [comment]
你好，请问现在问题解决了吗？

花晓轩 <notifications@github.com> 于2019年11月28日周四 下午5:34写道：
